version: '3.8'

services:
  template:
    volumes:
      - $LOGGER_VOLUME
    environment:
      ENCRYPT_KEY: $ENCRYPT_KEY
      SPRING_MAIN_BANNER_MODE: $SPRING_MAIN_BANNER_MODE
      CONFIG_ENABLED: $CONFIG_ENABLED
      CONFIG_PROFILE: $CONFIG_PROFILE
      CONFIG_SERVER: $CONFIG_SERVER
      EUREKA_URI: $EUREKA_URI
      TEMPLATE_NAME: $TEMPLATE_NAME
      TEMPLATE_PORT: $TEMPLATE_PORT
      KEYCLOAK_REALM: $KEYCLOAK_REALM
      KEYCLOAK_URI: $KEYCLOAK_URI
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      LOG_PATH: $LOG_PATH
    build: ""
    image: $TEMPLATE_IMAGE
#    deploy:
#      replicas: $TEMPLATE_REPLICAS
    container_name: $TEMPLATE_CONTAINER
    restart: always
    ports:
      - $TEMPLATE_PORT
    networks:
      cloud:
        ipv4_address: $TEMPLATE_IP
    dns:
      - 8.8.8.8
    healthcheck:
      test: nc -z -v 0.0.0.0 $TEMPLATE_PORT
      interval: 5s
      timeout: 1s
      retries: 3

networks:
  cloud:
    name: $NETWORK_NAME
    ipam:
      driver: default
      config:
        - subnet: $NETWORK_SUBNET
          gateway: $NETWORK_GATEWAY

