version: '3.8'

services:
  zuul:
    volumes:
      - $LOGGER_VOLUME
    environment:
      ENCRYPT_KEY: $ENCRYPT_KEY
      SPRING_MAIN_BANNER_MODE: $SPRING_MAIN_BANNER_MODE
      CONFIG_ENABLED: $CONFIG_ENABLED
      CONFIG_PROFILE: $CONFIG_PROFILE
      CONFIG_SERVER: $CONFIG_SERVER
      EUREKA_URI: $EUREKA_URI
      ZUUL_NAME: $ZUUL_NAME
      ZUUL_PORT: $ZUUL_PORT
      LOG_PATH: $LOG_PATH
    build: ""
    image: $ZUUL_IMAGE
    container_name: $ZUUL_CONTAINER
    restart: always
    ports:
      - $ZUUL_PORT:$ZUUL_PORT
    networks:
      cloud:
        ipv4_address: $ZUUL_IP
    healthcheck:
      test: nc -z -v 0.0.0.0 $ZUUL_PORT
      interval: 5s
      timeout: 1s
      retries: 3

networks:
  cloud:
    name: $NETWORK_NAME
    ipam:
      driver: default
      config:
        - subnet: $NETWORK_SUBNET
          gateway: $NETWORK_GATEWAY
