version: '3.8'

services:
  keycloak:
    build: .
    container_name: $KEYCLOAK_NAME
    image: $KEYCLOAK_IMAGE
    restart: always
    ports:
      - $KEYCLOAK_HTTP_PORT:$KEYCLOAK_HTTP_PORT
      - $KEYCLOAK_HTTPS_PORT:$KEYCLOAK_HTTPS_PORT
    networks:
      cloud:
        ipv4_address: $KEYCLOAK_IP
    healthcheck:
      test: nc -z -v 0.0.0.0 $KEYCLOAK_HTTP_PORT
      interval: 5s
      timeout: 1s
      retries: 3

networks:
  cloud:
    name: $NETWORK_NAME
    ipam:
      driver: default
      config:
        - subnet: $NETWORK_SUBNET
          gateway: $NETWORK_GATEWAY
