version: '3.8'

services:
  config:
    volumes:
      - $LOGGER_VOLUME
      - $CONFIG_REPO_MAP:$CONFIG_REPO
    environment:
      ENCRYPT_KEY: $ENCRYPT_KEY
      SPRING_MAIN_BANNER_MODE: $SPRING_MAIN_BANNER_MODE
      CONFIG_NAME: $CONFIG_NAME
      CONFIG_PORT: $CONFIG_PORT
      BUS_IP: $BUS_IP
      BUS_PORT: $BUS_PORT
      LOG_PATH: $LOG_PATH
    build: ""
    image: $CONFIG_IMAGE
    container_name: $CONFIG_CONTAINER
    restart: always
    ports:
      - $CONFIG_PORT:$CONFIG_PORT
    networks:
      cloud:
        ipv4_address: $CONFIG_IP
    healthcheck:
      test: nc -z -v 0.0.0.0 $CONFIG_PORT
      interval: 5s
      timeout: 1s
      retries: 3

networks:
  cloud:
    name: $NETWORK_NAME
    ipam:
      driver: default
      config:
        - subnet: $NETWORK_SUBNET
          gateway: $NETWORK_GATEWAY

