spring:
  application:
    name: ${CONFIG_NAME}
  cloud:
    config:
      server:
        git:
          uri: file://${CONFIG_REPO}
#    bus:
#      id: ${spring.application.name}:${spring.profiles.active}:${random.uuid}
#      enabled: true
#      refresh:
#        enabled: true
#      env:
#        enabled: true
#  profiles:
#    active: dev

  rabbitmq:
    host: ${BUS_IP}
    port: ${BUS_PORT}
    username: guest
    password: '{cipher}efc685687f9cbae23670ff364a29d896a8252bac45c78a143cce826a59c0914a'
#    addresses: ${BUS_IP}:${BUS_PORT}

server:
  port: ${CONFIG_PORT}

info:
  component: Configuration
  description: Configuration Server
  
logging:
  level:
    root: INFO
  path: ${LOG_PATH}
  file:
    name: ${logging.path}/${spring.application.name}.log
