filebeat.inputs:
  - type: log
    paths:
      - "/var/log/integration/*.log.json"
    json.keys_under_root: true
    json.overwrite_keys: false
    json.add_error_key: true

# setup filebeat to send output to logstash
#output.logstash:
#  hosts: ["${LOGSTASH}"]
#  index: filebeat

output.elasticsearch:
  hosts: ["${ELASTICSEARCH}"]
  index: "cloud-%{+yyyy.MM.dd}"
setup.template:
  name: 'cloud'
  pattern: 'cloud-*'
  enabled: false
