version: '3.8'

services:
  ui-1:
    volumes:
      - $LOGGER_VOLUME
    environment:
      ENCRYPT_KEY: $ENCRYPT_KEY
      SPRING_MAIN_BANNER_MODE: $SPRING_MAIN_BANNER_MODE
      AUTH_USERNAME: $AUTH_USERNAME
      AUTH_PASSWORD: $AUTH_PASSWORD
      SERVICE_GATEWAY: $SERVICE_GATEWAY
      KEYCLOAK_REALM: $KEYCLOAK_REALM
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      CLIENT_SCOPE: $CLIENT_SCOPE
      KEYCLOAK_URL: $KEYCLOAK_URL
      UI1_NAME: $UI1_NAME
      UI1_IP: $UI1_IP
      UI1_PORT: $UI1_PORT
      LOG_PATH: $LOG_PATH
    build: ""
    image: $UI1_IMAGE
    container_name: $UI1_CONTAINER
    restart: always
    ports:
      - $UI1_PORT:$UI1_PORT
    networks:
      cloud:
        ipv4_address: $UI1_IP
    healthcheck:
      test: nc -z -v 0.0.0.0 $UI1_PORT
      interval: 5s
      timeout: 1s
      retries: 3

networks:
  cloud:
    name: $NETWORK_NAME
    ipam:
      driver: default
      config:
        - subnet: $NETWORK_SUBNET
          gateway: $NETWORK_GATEWAY
